"ENVIRONMENT": "dev",
"CASSANDRA_HOST": "cassandra",
"CASSANDRA_KEYSPACE": "test",
"CASSANDRA_USERNAME": "user",
"CASSANDRA_PASSWORD": "pwd",
"FEATURE_STORE_S3_BUCKET": "bucket",
"FEATURE_STORE_HISTORICAL_DATABASE": "database"
