name: "Test"
on:
  push:
    branches:
      - master
      - staging
  pull_request:

jobs:
  Pipeline:
    runs-on: ubuntu-16.04
    container: rappdw/docker-java-python

    steps:
    - uses: actions/checkout@v2

#    - name: Install dependencies
#      run: make ci-install
#
#    - name: Style check
#      run: PYTHONPATH=./pip/deps make style-check
#
#    - name: Quality check
#      run: PYTHONPATH=./pip/deps make quality-check
#
#    - name: Tests
#      run: PYTHONPATH=./pip/deps make tests

    - name: Setup sonarqube
      uses: warchant/setup-sonar-scanner@v1

    - name: Run sonarqube
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        SONAR_PASSWORD: ${{ secrets.SONAR_PASSWORD }}}
        PR_NUMBER: ${{ github.event.number }}
      run: sonar-scanner
          -Dsonar.projectName=Butterfree \
          -Dsonar.projectKey=butterfree \
          -Dsonar.projectBaseDir=. \
          -Dsonar.sources=./butterfree \
          -Dsonar.sourceEncoding=UTF-8 \
          -Dsonar.analysis.mode=preview \
          -Dsonar.github.pullRequest=$PR_NUMBER \
          -Dsonar.github.repository=quintoandar/butterfree \
          -Dsonar.github.oauth=$GITHUB_TOKEN \
          -Dsonar.host.url=https://sonar.quintoandar.com.br \
          -Dsonar.login=user \
          -Dsonar.password=$SONAR_PASSWORD
